# Perfil de desarrollo
spring.datasource.url=jdbc:postgresql://localhost:5432/dresscode_database
spring.datasource.username=postgres
spring.jpa.show-sql=true
spring.security.enabled=false
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET}
mercadopago.access-token=${MP_ACCESS_TOKEN}
mercadopago.webhook-secret=${MP_WEBHOOK_SECRET}
logging.level.org.springframework.security=DEBUG
logging.level.com.dresscode.api_dresscode.Jwt=DEBUG
